server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: lecture
          uri: http://localhost:8082
          predicates:
            - Path=/lectures/**, /getLetcures/**
        - id: user
          uri: http://localhost:8083
          predicates:
            - Path=/users/**, 
        - id: study
          uri: http://localhost:8084
          predicates:
            - Path=/studies/**, 
        - id: lecturesupport
          uri: http://localhost:8085
          predicates:
            - Path=/assignments/**, /lectureSuggestions/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: lecture
          uri: http://lecture:8080
          predicates:
            - Path=/lectures/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: study
          uri: http://study:8080
          predicates:
            - Path=/studies/**, 
        - id: lecturesupport
          uri: http://lecturesupport:8080
          predicates:
            - Path=/assignments/**, /lectureSuggestions/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
